export const permissionMap: Record<string, Record<string, "A" | "R" | "N">> = {
  ติดตามกระบวนการขาย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  การติดตามตัวชี้วัดสำคัญ: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "N",
    Accounting: "A",
  },
  คาดการณ์ยอดขาย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "N",
    Accounting: "A",
  },
  รายงาน: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "N",
    Accounting: "A",
  },
  การจัดการลูกค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  กำหนดข้อมูลพื้นฐานลูกค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "N",
    Accounting: "A",
  },
  กลุ่มแท็ก: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  นิสัย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  บทบาทลูกค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  บันทึกกิจกรรม: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ช่องทางการติดต่อ: {
    Admin: "A",
    Owner: "N",
    Manager: "N",
    Technician: "N",
    Sale: "N",
    Accounting: "N",
  },
  ใบเสนอราคา: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  อนุมัติใบเสนอราคา: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ใบสั่งขาย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  สินค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  กลุ่มสินค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  หน่วยสินค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  การจัดการข้อมูลบริษัท: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "N",
    Accounting: "A",
  },
  พนักงาน: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "N",
    Accounting: "A",
  },
  การจัดการทีม: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "N",
    Accounting: "A",
  },
  สิทธิการเข้าถึง: {
    Admin: "A",
    Owner: "N",
    Manager: "N",
    Technician: "N",
    Sale: "N",
    Accounting: "N",
  },
  สถานะพนักงาน: {
    Admin: "A",
    Owner: "A",
    Manager: "N",
    Technician: "N",
    Sale: "N",
    Accounting: "N",
  },
  ภาษี: {
    Admin: "A",
    Owner: "N",
    Manager: "N",
    Technician: "N",
    Sale: "N",
    Accounting: "N",
  },
  สกุลเงิน: {
    Admin: "A",
    Owner: "N",
    Manager: "N",
    Technician: "N",
    Sale: "N",
    Accounting: "N",
  },
  ช่องทางการชำระเงิน: {
    Admin: "A",
    Owner: "N",
    Manager: "N",
    Technician: "N",
    Sale: "N",
    Accounting: "N",
  },
  กลุ่มโซเชียล: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  บริษัท: {
    Admin: "A",
    Owner: "A",
    Manager: "N",
    Technician: "N",
    Sale: "N",
    Accounting: "N",
  },
  บทบาท: {
    Admin: "A",
    Owner: "A",
    Manager: "N",
    Technician: "N",
    Sale: "N",
    Accounting: "N",
  },

  
};
